export const ErrorCodeEnum = {
    // Authentication Errors
    AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
    AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
    AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
    AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
    AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
    AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
    AUTH_ACCOUNT_DISABLED: "AUTH_ACCOUNT_DISABLED",

    // Access Control Errors
    ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",
    ACCESS_FORBIDDEN: "ACCESS_FORBIDDEN",
    ACCESS_ROLE_REQUIRED: "ACCESS_ROLE_REQUIRED",
    ACCESS_PERMISSION_DENIED: "ACCESS_PERMISSION_DENIED",

    // Validation Errors
    VALIDATION_ERROR: "VALIDATION_ERROR",
    VALIDATION_FAILED: "VALIDATION_FAILED",
    INVALID_INPUT: "INVALID_INPUT",
    MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
    INVALID_FORMAT: "INVALID_FORMAT",
    INVALID_PARAMETERS: "INVALID_PARAMETERS",

    // Resource Errors
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
    RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
    RESOURCE_LOCKED: "RESOURCE_LOCKED",
    RESOURCE_GONE: "RESOURCE_GONE",

    // Request / API Errors
    BAD_REQUEST: "BAD_REQUEST",
    METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
    NOT_ACCEPTABLE: "NOT_ACCEPTABLE",
    REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",

    // External / Integration Errors
    EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    DEPENDENCY_TIMEOUT: "DEPENDENCY_TIMEOUT",
    THIRD_PARTY_FAILURE: "THIRD_PARTY_FAILURE",

    // Database Errors
    DB_CONNECTION_FAILED: "DB_CONNECTION_FAILED",
    DB_QUERY_FAILED: "DB_QUERY_FAILED",
    DB_CONSTRAINT_VIOLATION: "DB_CONSTRAINT_VIOLATION",
    DB_TRANSACTION_FAILED: "DB_TRANSACTION_FAILED",

    // System Errors
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
    CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type TErrorCodeEnum = (typeof ErrorCodeEnum)[keyof typeof ErrorCodeEnum];
